"""Regenera la parte autogenerada del baseline 0001 a partir de los modelos.

USO EXCLUSIVO ANTES DEL PRIMER DESPLIEGUE CON ALEMBIC. Mientras ninguna base
de produccion tenga la tabla `alembic_version`, el baseline puede rehacerse para
absorber cambios de modelos hechos en paralelo (la prueba
`test_alembic_schema_matches_models` avisa cuando hace falta). Despues del
primer despliegue el baseline queda congelado y todo cambio va en una revision
nueva (`alembic revision --autogenerate -m "..."`, ver DEPLOY.md).

Conserva lo escrito a mano en 0001_baseline.py (encabezado, indices pg_trgm,
downgrade de esos indices) y reemplaza solo:
- los bloques entre "# ### commands auto generated" y "# ### end Alembic commands ###";
- la tupla BASELINE_TABLES.

Uso, desde backend/:
    .\\.venv\\Scripts\\python.exe alembic\\regenerate_baseline.py
"""
from __future__ import annotations

import re
import shutil
import sys
import tempfile
import textwrap
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND_DIR))

from alembic import command  # noqa: E402
from alembic.config import Config  # noqa: E402

BASELINE = BACKEND_DIR / "alembic" / "versions" / "0001_baseline.py"
AUTO_BLOCK = re.compile(
    r"    # ### commands auto generated by Alembic - please adjust! ###\n"
    r".*?"
    r"    # ### end Alembic commands ###\n",
    re.S,
)
TABLES_BLOCK = re.compile(r"BASELINE_TABLES = \(\n.*?\n\)\n", re.S)


def _generate(tmp: Path) -> str:
    script_dir = tmp / "alembic"
    shutil.copytree(
        BACKEND_DIR / "alembic",
        script_dir,
        ignore=shutil.ignore_patterns("versions", "__pycache__", "regenerate_baseline.py"),
    )
    (script_dir / "versions").mkdir()
    cfg = Config(str(BACKEND_DIR / "alembic.ini"))
    cfg.set_main_option("script_location", str(script_dir).replace("%", "%%"))
    cfg.attributes["database_url"] = f"sqlite:///{(tmp / 'vacia.db').as_posix()}"
    command.revision(cfg, message="baseline", autogenerate=True, rev_id="0001")
    return next((script_dir / "versions").glob("0001_*.py")).read_text(encoding="utf-8")


def main() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        generated = _generate(Path(tmp))

    # El autogenerate emite Text() sin prefijo dentro de JSONB(astext_type=...).
    generated = generated.replace("astext_type=Text()", "astext_type=sa.Text()")
    new_blocks = AUTO_BLOCK.findall(generated)
    current = BASELINE.read_text(encoding="utf-8")
    old_blocks = AUTO_BLOCK.findall(current)
    if len(new_blocks) != 2 or len(old_blocks) != 2:
        print("No se encontraron los dos bloques autogenerados (upgrade/downgrade).", file=sys.stderr)
        return 1

    it = iter(new_blocks)
    updated = AUTO_BLOCK.sub(lambda _m: next(it), current)

    tables = re.findall(r"op\.create_table\('([a-z0-9_]+)'", new_blocks[0])
    body = textwrap.fill(", ".join(repr(t) for t in tables) + ",", width=76,
                         initial_indent="    ", subsequent_indent="    ")
    updated = TABLES_BLOCK.sub(lambda _m: f"BASELINE_TABLES = (\n{body}\n)\n", updated)

    before = set(re.findall(r"op\.create_table\('([a-z0-9_]+)'", old_blocks[0]))
    BASELINE.write_text(updated, encoding="utf-8", newline="\n")
    print(f"Baseline regenerado: {len(tables)} tablas.")
    if set(tables) - before:
        print("  tablas nuevas:", ", ".join(sorted(set(tables) - before)))
    if before - set(tables):
        print("  tablas retiradas:", ", ".join(sorted(before - set(tables))))
    print("Revise el diff (git diff) y ejecute: python -m pytest tests/test_frente_d_migrations.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
