"""Baseline: esquema completo de la v6 (fase 0, P0-1).

Revision ID: 0001
Revises:
Create Date: 2026-09-10 13:37:42.585548

Generada con `alembic revision --autogenerate` contra una base SQLite vacia y
revisada a mano. Representa exactamente lo que producen
`Base.metadata.create_all` + `run_schema_migrations` sobre los modelos de
`app/models.py` en esta version. Se agrega, solo en PostgreSQL, el indice GIN
con `pg_trgm` del indice regulatorio de INVIMA (P1-3).

- Base vacia: `alembic upgrade head` ejecuta este archivo.
- Base existente creada antes de Alembic: `app.migrations.upgrade_database()`
  la marca (stamp) en esta revision sin ejecutarla y crea aparte, de forma
  idempotente, los indices trigram (ver `ensure_trgm_indexes`).

No incluye los disparadores de solo insercion de `audit_log`: los instala
`database.harden_audit_log()` en cada arranque (triggers en SQLite, REVOKE en
PostgreSQL), igual que antes de Alembic.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Identificadores de la revision, usados por Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Tablas que crea este baseline. `app.migrations` las usa para completar una
# base anterior a Alembic antes de marcarla, sin crear tablas de revisiones
# posteriores. La prueba test_frente_d_migrations verifica que coincidan.
BASELINE_TABLES = (
    'app_meta', 'audit_log', 'chat_sessions', 'clusters', 'invima_records',
    'invima_syncs', 'methodology_params', 'notes', 'priority_criteria',
    'scheduled_runs', 'sources', 'tech_types', 'users', 'alert_events',
    'alert_subscriptions', 'chat_messages', 'cycles', 'findings',
    'ingest_jobs', 'scrape_logs', 'bulletins', 'cycle_datamarts',
    'recommendations', 'strategy_graphs', 'technologies',
    'cycle_technologies', 'evaluation_docs', 'merge_proposals',
    'novelty_assessments', 'priority_scores', 'raw_records', 'submissions',
    'ttm_snapshots', 'evaluation_versions', 'review_assignments',
    'review_comments',
)


# --------------------------------------------------------------------------- #
#  P1-3: similitud en el motor (pg_trgm + GIN) sobre el indice de INVIMA
# --------------------------------------------------------------------------- #
# El prefiltro de `invima.search` es `producto_norm LIKE '%x%' OR
# principio_norm LIKE '%x%'`. Un B-tree no sirve para comodines a la izquierda;
# un GIN con gin_trgm_ops si. Los nombres coinciden con MANUAL_INDEXES de env.py
# para que el autogenerate no proponga borrarlos (no estan en los modelos,
# que siguen siendo portables a SQLite).
TRGM_INDEXES = (
    ("ix_invima_records_producto_norm_trgm", "invima_records", "producto_norm"),
    ("ix_invima_records_principio_norm_trgm", "invima_records", "principio_norm"),
)


def trgm_statements() -> list[str]:
    """SQL idempotente de la extension y de los indices trigram (PostgreSQL)."""
    stmts = ["CREATE EXTENSION IF NOT EXISTS pg_trgm"]
    for name, table, column in TRGM_INDEXES:
        stmts.append(
            f"CREATE INDEX IF NOT EXISTS {name} ON {table} USING gin ({column} gin_trgm_ops)"
        )
    return stmts


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_meta',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_role', sa.String(length=40), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('old_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('new_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('request_path', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_email'), ['user_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('node_key', sa.String(length=120), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('graph_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_graph_id'), ['graph_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_node_key'), ['node_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_email'), ['user_email'], unique=False)

    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('icd10_prefixes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('mesh_terms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clusters_code'), ['code'], unique=True)

    op.create_table('invima_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediente', sa.String(length=120), nullable=False),
    sa.Column('registro', sa.String(length=120), nullable=False),
    sa.Column('producto', sa.String(length=500), nullable=False),
    sa.Column('titular', sa.String(length=400), nullable=False),
    sa.Column('principio_activo', sa.String(length=600), nullable=False),
    sa.Column('atc_code', sa.String(length=40), nullable=False),
    sa.Column('forma_farmaceutica', sa.String(length=300), nullable=False),
    sa.Column('estado_registro', sa.String(length=120), nullable=False),
    sa.Column('fecha_expedicion', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('producto_norm', sa.String(length=500), nullable=False),
    sa.Column('principio_norm', sa.String(length=600), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invima_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invima_records_atc_code'), ['atc_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_invima_records_estado_registro'), ['estado_registro'], unique=False)
        batch_op.create_index(batch_op.f('ix_invima_records_expediente'), ['expediente'], unique=False)
        batch_op.create_index(batch_op.f('ix_invima_records_principio_norm'), ['principio_norm'], unique=False)
        batch_op.create_index(batch_op.f('ix_invima_records_producto_norm'), ['producto_norm'], unique=False)
        batch_op.create_index(batch_op.f('ix_invima_records_registro'), ['registro'], unique=False)

    op.create_table('invima_syncs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_ingested', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('methodology_params',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.String(length=300), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_author_email'), ['author_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_entity_type'), ['entity_type'], unique=False)

    op.create_table('priority_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('short_label', sa.String(length=120), nullable=False),
    sa.Column('role_scope', sa.String(length=60), nullable=False),
    sa.Column('auto_prefill', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_reference', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_criterion_version')
    )
    with op.batch_alter_table('priority_criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priority_criteria_code'), ['code'], unique=False)

    op.create_table('scheduled_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_found', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_runs_task'), ['task'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('authors', sa.String(length=600), nullable=False),
    sa.Column('year', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('relation_iets', sa.String(length=300), nullable=False),
    sa.Column('language', sa.String(length=60), nullable=False),
    sa.Column('resource_type', sa.String(length=120), nullable=False),
    sa.Column('link_status', sa.String(length=120), nullable=False),
    sa.Column('scrape_enabled', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.String(length=600), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connector', sa.String(length=60), nullable=False),
    sa.Column('connector_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('scan_interval_hours', sa.Integer(), nullable=False),
    sa.Column('failure_streak', sa.Integer(), nullable=False),
    sa.Column('circuit_open_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('catalog_code', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('access_level', sa.String(length=8), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('sync_frequency', sa.String(length=40), nullable=False),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('requires_api_key', sa.Boolean(), nullable=False),
    sa.Column('terms_url', sa.String(length=1024), nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('robots_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('robots_allowed', sa.Boolean(), nullable=True),
    sa.Column('health_status', sa.String(length=20), nullable=False),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schema_signature', sa.String(length=120), nullable=False),
    sa.Column('provides_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('aliases', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('verification_status', sa.String(length=40), nullable=False),
    sa.Column('catalog_note', sa.Text(), nullable=False),
    sa.Column('is_contrast', sa.Boolean(), nullable=False),
    sa.Column('catalog_active', sa.Boolean(), nullable=False),
    sa.Column('retired', sa.Boolean(), nullable=False),
    sa.Column('last_probe_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_probe_detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('next_review_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_access_level'), ['access_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_catalog_code'), ['catalog_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_connector'), ['connector'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_health_status'), ['health_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_title'), ['title'], unique=False)

    op.create_table('tech_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('legacy_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tech_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tech_types_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('picture', sa.String(length=1024), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_technology_id'), ['technology_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_user_id'), ['user_id'], unique=False)

    op.create_table('alert_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cluster_id', name='uq_alert_sub_user_cluster')
    )
    with op.batch_alter_table('alert_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_subscriptions_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources_used', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('opened_on', sa.Date(), nullable=False),
    sa.Column('data_cutoff_on', sa.Date(), nullable=False),
    sa.Column('bulletin_due_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('is_historic', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycles_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_cycles_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cycles_year'), ['year'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('technology', sa.String(length=400), nullable=False),
    sa.Column('technology_type', sa.String(length=120), nullable=False),
    sa.Column('horizon', sa.String(length=60), nullable=False),
    sa.Column('phase', sa.String(length=120), nullable=False),
    sa.Column('therapeutic_area', sa.String(length=300), nullable=False),
    sa.Column('published_date', sa.String(length=60), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('screening_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'content_hash', name='uq_finding_hash')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_horizon'), ['horizon'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_title'), ['title'], unique=False)

    op.create_table('ingest_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_found', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingest_jobs_connector'), ['connector'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_jobs_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_jobs_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_jobs_status'), ['status'], unique=False)

    op.create_table('scrape_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('items_found', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_logs_source_id'), ['source_id'], unique=False)

    op.create_table('bulletins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('compiled_by', sa.String(length=255), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bulletins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulletins_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulletins_status'), ['status'], unique=False)

    op.create_table('cycle_datamarts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('impact', sa.String(length=60), nullable=False),
    sa.Column('model_used', sa.String(length=120), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_finding_id'), ['finding_id'], unique=False)

    op.create_table('strategy_graphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_graphs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_graphs_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_graphs_user_email'), ['user_email'], unique=False)

    op.create_table('technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commercial_name', sa.String(length=400), nullable=False),
    sa.Column('inn_name', sa.String(length=400), nullable=False),
    sa.Column('manufacturer', sa.String(length=300), nullable=False),
    sa.Column('nct_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('indication', sa.Text(), nullable=False),
    sa.Column('mechanism', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('tech_type_id', sa.Integer(), nullable=True),
    sa.Column('suggested_cluster_id', sa.Integer(), nullable=True),
    sa.Column('suggested_cluster_reason', sa.String(length=400), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('horizon', sa.String(length=60), nullable=False),
    sa.Column('atc_code', sa.String(length=40), nullable=False),
    sa.Column('icd10_codes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('mesh_terms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('device_nomenclature', sa.String(length=120), nullable=False),
    sa.Column('phase3_completion_date', sa.Date(), nullable=True),
    sa.Column('fda_approval_date', sa.Date(), nullable=True),
    sa.Column('ema_approval_date', sa.Date(), nullable=True),
    sa.Column('invima_registry', sa.String(length=200), nullable=False),
    sa.Column('regulatory_status', sa.String(length=120), nullable=False),
    sa.Column('development_phase', sa.String(length=120), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source_channel', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('captured_by', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('screening_score', sa.Integer(), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tech_type_id'], ['tech_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id')
    )
    with op.batch_alter_table('technologies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technologies_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_technologies_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_technologies_commercial_name'), ['commercial_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_technologies_condition'), ['condition'], unique=False)
        batch_op.create_index(batch_op.f('ix_technologies_inn_name'), ['inn_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_technologies_merged_into_id'), ['merged_into_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_technologies_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_technologies_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_technologies_tech_type_id'), ['tech_type_id'], unique=False)

    op.create_table('cycle_technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('priority_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('priority_points', sa.SmallInteger(), nullable=True),
    sa.Column('frozen', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason_code', sa.String(length=60), nullable=False),
    sa.Column('exclusion_note', sa.Text(), nullable=False),
    sa.Column('excluded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excluded_by', sa.String(length=255), nullable=False),
    sa.Column('carried_from_cycle_id', sa.Integer(), nullable=True),
    sa.Column('previous_priority_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_by', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'technology_id', name='uq_cycle_technology')
    )
    with op.batch_alter_table('cycle_technologies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_technologies_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cycle_technologies_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cycle_technologies_technology_id'), ['technology_id'], unique=False)

    op.create_table('evaluation_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('product_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('confidential', sa.Boolean(), nullable=False),
    sa.Column('confidential_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('version_major', sa.Integer(), nullable=False),
    sa.Column('version_minor', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'technology_id', name='uq_eval_doc_per_cycle')
    )
    with op.batch_alter_table('evaluation_docs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_docs_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_docs_product_level'), ['product_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_docs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_docs_technology_id'), ['technology_id'], unique=False)

    op.create_table('merge_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technology_a_id', sa.Integer(), nullable=False),
    sa.Column('technology_b_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('decisive', sa.Boolean(), nullable=False),
    sa.Column('matched_on', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('kept_technology_id', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('resolved_by', sa.String(length=255), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('technology_a_id < technology_b_id', name='ck_merge_pair_order'),
    sa.ForeignKeyConstraint(['technology_a_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_b_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technology_a_id', 'technology_b_id', name='uq_merge_pair')
    )
    with op.batch_alter_table('merge_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merge_proposals_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_merge_proposals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_merge_proposals_technology_a_id'), ['technology_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_merge_proposals_technology_b_id'), ['technology_b_id'], unique=False)

    op.create_table('novelty_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('option_code', sa.String(length=60), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('invima_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invima_match_count', sa.Integer(), nullable=False),
    sa.Column('invima_best_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('invima_registry', sa.String(length=200), nullable=False),
    sa.Column('invima_holder', sa.String(length=300), nullable=False),
    sa.Column('invima_status', sa.String(length=120), nullable=False),
    sa.Column('has_valid_registry', sa.Boolean(), nullable=False),
    sa.Column('sala_especializada_concept', sa.Text(), nullable=False),
    sa.Column('sala_especializada_ref', sa.String(length=300), nullable=False),
    sa.Column('assessed_by', sa.String(length=255), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'technology_id', name='uq_novelty_per_cycle')
    )
    with op.batch_alter_table('novelty_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_novelty_assessments_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_novelty_assessments_option_code'), ['option_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_novelty_assessments_technology_id'), ['technology_id'], unique=False)

    op.create_table('priority_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('criterion', sa.String(length=10), nullable=False),
    sa.Column('criterion_version', sa.Integer(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('auto_suggested', sa.SmallInteger(), nullable=True),
    sa.Column('auto_reason', sa.String(length=400), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('rated_by', sa.Integer(), nullable=True),
    sa.Column('rated_by_email', sa.String(length=255), nullable=False),
    sa.Column('rated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('value IN (0, 1)', name='ck_priority_binary'),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'technology_id', 'criterion', name='uq_priority_score')
    )
    with op.batch_alter_table('priority_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priority_scores_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_priority_scores_technology_id'), ['technology_id'], unique=False)

    op.create_table('raw_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector', sa.String(length=60), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('payload_hash', sa.String(length=80), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('technology_id', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reprocessed_count', sa.Integer(), nullable=False),
    sa.Column('adapter_version', sa.String(length=40), nullable=False),
    sa.Column('endpoint', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector', 'external_id', name='uq_raw_connector_external')
    )
    with op.batch_alter_table('raw_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_records_connector'), ['connector'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_records_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_records_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_records_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_records_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_records_payload_hash'), ['payload_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_records_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_records_technology_id'), ['technology_id'], unique=False)

    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commercial_name', sa.String(length=400), nullable=False),
    sa.Column('inn_name', sa.String(length=400), nullable=False),
    sa.Column('mechanism', sa.Text(), nullable=False),
    sa.Column('manufacturer', sa.String(length=300), nullable=False),
    sa.Column('indication', sa.Text(), nullable=False),
    sa.Column('development_phase', sa.String(length=120), nullable=False),
    sa.Column('evidence_links', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('conflict_statement', sa.Text(), nullable=False),
    sa.Column('submitter_name', sa.String(length=255), nullable=False),
    sa.Column('submitter_email', sa.String(length=255), nullable=False),
    sa.Column('submitter_org', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('technology_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_commercial_name'), ['commercial_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_submitter_email'), ['submitter_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_technology_id'), ['technology_id'], unique=False)

    op.create_table('ttm_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('months', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('band', sa.String(length=40), nullable=False),
    sa.Column('basis', sa.String(length=80), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'technology_id', name='uq_ttm_cycle_tech')
    )
    with op.batch_alter_table('ttm_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ttm_snapshots_band'), ['band'], unique=False)
        batch_op.create_index(batch_op.f('ix_ttm_snapshots_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ttm_snapshots_technology_id'), ['technology_id'], unique=False)

    op.create_table('evaluation_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('major', sa.Integer(), nullable=False),
    sa.Column('minor', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['evaluation_docs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_versions_doc_id'), ['doc_id'], unique=False)

    op.create_table('review_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('reviewer_name', sa.String(length=255), nullable=False),
    sa.Column('reviewer_email', sa.String(length=255), nullable=False),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.String(length=80), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coi_signed', sa.Boolean(), nullable=False),
    sa.Column('coi_statement', sa.Text(), nullable=False),
    sa.Column('coi_has_conflict', sa.Boolean(), nullable=False),
    sa.Column('coi_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['evaluation_docs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_assignments_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_assignments_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_assignments_reviewer_email'), ['reviewer_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_assignments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_assignments_token_hash'), ['token_hash'], unique=False)

    op.create_table('review_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('field_key', sa.String(length=80), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['evaluation_docs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_comments_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_comments_doc_id'), ['doc_id'], unique=False)

    # ### end Alembic commands ###

    # Solo PostgreSQL: en SQLite la busqueda sigue con el B-tree y LIKE.
    # `op.get_context().dialect` funciona tambien en modo --sql (sin conexion).
    if op.get_context().dialect.name == "postgresql":
        for stmt in trgm_statements():
            op.execute(stmt)


def downgrade() -> None:
    if op.get_context().dialect.name == "postgresql":
        for name, _table, _column in TRGM_INDEXES:
            op.execute(f"DROP INDEX IF EXISTS {name}")
        # La extension pg_trgm se deja instalada: la usa tambien ensure_pg_extensions.

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_comments_doc_id'))
        batch_op.drop_index(batch_op.f('ix_review_comments_assignment_id'))

    op.drop_table('review_comments')
    with op.batch_alter_table('review_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_assignments_token_hash'))
        batch_op.drop_index(batch_op.f('ix_review_assignments_status'))
        batch_op.drop_index(batch_op.f('ix_review_assignments_reviewer_email'))
        batch_op.drop_index(batch_op.f('ix_review_assignments_kind'))
        batch_op.drop_index(batch_op.f('ix_review_assignments_doc_id'))

    op.drop_table('review_assignments')
    with op.batch_alter_table('evaluation_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_versions_doc_id'))

    op.drop_table('evaluation_versions')
    with op.batch_alter_table('ttm_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ttm_snapshots_technology_id'))
        batch_op.drop_index(batch_op.f('ix_ttm_snapshots_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_ttm_snapshots_band'))

    op.drop_table('ttm_snapshots')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_technology_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_submitter_email'))
        batch_op.drop_index(batch_op.f('ix_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_submissions_created_at'))
        batch_op.drop_index(batch_op.f('ix_submissions_commercial_name'))

    op.drop_table('submissions')
    with op.batch_alter_table('raw_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_records_technology_id'))
        batch_op.drop_index(batch_op.f('ix_raw_records_source_id'))
        batch_op.drop_index(batch_op.f('ix_raw_records_payload_hash'))
        batch_op.drop_index(batch_op.f('ix_raw_records_job_id'))
        batch_op.drop_index(batch_op.f('ix_raw_records_finding_id'))
        batch_op.drop_index(batch_op.f('ix_raw_records_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_raw_records_external_id'))
        batch_op.drop_index(batch_op.f('ix_raw_records_connector'))

    op.drop_table('raw_records')
    with op.batch_alter_table('priority_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priority_scores_technology_id'))
        batch_op.drop_index(batch_op.f('ix_priority_scores_cycle_id'))

    op.drop_table('priority_scores')
    with op.batch_alter_table('novelty_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_novelty_assessments_technology_id'))
        batch_op.drop_index(batch_op.f('ix_novelty_assessments_option_code'))
        batch_op.drop_index(batch_op.f('ix_novelty_assessments_cycle_id'))

    op.drop_table('novelty_assessments')
    with op.batch_alter_table('merge_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merge_proposals_technology_b_id'))
        batch_op.drop_index(batch_op.f('ix_merge_proposals_technology_a_id'))
        batch_op.drop_index(batch_op.f('ix_merge_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_merge_proposals_cycle_id'))

    op.drop_table('merge_proposals')
    with op.batch_alter_table('evaluation_docs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_docs_technology_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_docs_status'))
        batch_op.drop_index(batch_op.f('ix_evaluation_docs_product_level'))
        batch_op.drop_index(batch_op.f('ix_evaluation_docs_cycle_id'))

    op.drop_table('evaluation_docs')
    with op.batch_alter_table('cycle_technologies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_technologies_technology_id'))
        batch_op.drop_index(batch_op.f('ix_cycle_technologies_status'))
        batch_op.drop_index(batch_op.f('ix_cycle_technologies_cycle_id'))

    op.drop_table('cycle_technologies')
    with op.batch_alter_table('technologies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technologies_tech_type_id'))
        batch_op.drop_index(batch_op.f('ix_technologies_status'))
        batch_op.drop_index(batch_op.f('ix_technologies_source_id'))
        batch_op.drop_index(batch_op.f('ix_technologies_merged_into_id'))
        batch_op.drop_index(batch_op.f('ix_technologies_inn_name'))
        batch_op.drop_index(batch_op.f('ix_technologies_condition'))
        batch_op.drop_index(batch_op.f('ix_technologies_commercial_name'))
        batch_op.drop_index(batch_op.f('ix_technologies_cluster_id'))
        batch_op.drop_index(batch_op.f('ix_technologies_captured_at'))

    op.drop_table('technologies')
    with op.batch_alter_table('strategy_graphs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_graphs_user_email'))
        batch_op.drop_index(batch_op.f('ix_strategy_graphs_cycle_id'))

    op.drop_table('strategy_graphs')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_finding_id'))

    op.drop_table('recommendations')
    op.drop_table('cycle_datamarts')
    with op.batch_alter_table('bulletins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulletins_status'))
        batch_op.drop_index(batch_op.f('ix_bulletins_cycle_id'))

    op.drop_table('bulletins')
    with op.batch_alter_table('scrape_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_logs_source_id'))

    op.drop_table('scrape_logs')
    with op.batch_alter_table('ingest_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingest_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_ingest_jobs_source_id'))
        batch_op.drop_index(batch_op.f('ix_ingest_jobs_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_ingest_jobs_connector'))

    op.drop_table('ingest_jobs')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_title'))
        batch_op.drop_index(batch_op.f('ix_findings_source_id'))
        batch_op.drop_index(batch_op.f('ix_findings_horizon'))
        batch_op.drop_index(batch_op.f('ix_findings_content_hash'))

    op.drop_table('findings')
    with op.batch_alter_table('cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycles_year'))
        batch_op.drop_index(batch_op.f('ix_cycles_status'))
        batch_op.drop_index(batch_op.f('ix_cycles_code'))

    op.drop_table('cycles')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('alert_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_subscriptions_cluster_id'))

    op.drop_table('alert_subscriptions')
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_events_technology_id'))
        batch_op.drop_index(batch_op.f('ix_alert_events_kind'))
        batch_op.drop_index(batch_op.f('ix_alert_events_created_at'))

    op.drop_table('alert_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tech_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tech_types_code'))

    op.drop_table('tech_types')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_title'))
        batch_op.drop_index(batch_op.f('ix_sources_health_status'))
        batch_op.drop_index(batch_op.f('ix_sources_entity_type'))
        batch_op.drop_index(batch_op.f('ix_sources_connector'))
        batch_op.drop_index(batch_op.f('ix_sources_category'))
        batch_op.drop_index(batch_op.f('ix_sources_catalog_code'))
        batch_op.drop_index(batch_op.f('ix_sources_access_level'))

    op.drop_table('sources')
    with op.batch_alter_table('scheduled_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_runs_task'))
        batch_op.drop_index(batch_op.f('ix_scheduled_runs_status'))
        batch_op.drop_index(batch_op.f('ix_scheduled_runs_started_at'))

    op.drop_table('scheduled_runs')
    with op.batch_alter_table('priority_criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priority_criteria_code'))

    op.drop_table('priority_criteria')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_entity_type'))
        batch_op.drop_index(batch_op.f('ix_notes_entity_id'))
        batch_op.drop_index(batch_op.f('ix_notes_author_email'))

    op.drop_table('notes')
    op.drop_table('methodology_params')
    op.drop_table('invima_syncs')
    with op.batch_alter_table('invima_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invima_records_registro'))
        batch_op.drop_index(batch_op.f('ix_invima_records_producto_norm'))
        batch_op.drop_index(batch_op.f('ix_invima_records_principio_norm'))
        batch_op.drop_index(batch_op.f('ix_invima_records_expediente'))
        batch_op.drop_index(batch_op.f('ix_invima_records_estado_registro'))
        batch_op.drop_index(batch_op.f('ix_invima_records_atc_code'))

    op.drop_table('invima_records')
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clusters_code'))

    op.drop_table('clusters')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_email'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_scope'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_node_key'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_graph_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_cycle_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_user_email'))
        batch_op.drop_index(batch_op.f('ix_audit_log_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))

    op.drop_table('audit_log')
    op.drop_table('app_meta')
    # ### end Alembic commands ###
